# Generated by Django 3.1 on 2020-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('sub_category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=80)),
                ('customer_firstname', models.CharField(blank=True, max_length=20)),
                ('customer_lastname', models.CharField(blank=True, max_length=20)),
                ('customer_dob', models.DateField(blank=True)),
                ('customer_gender', models.CharField(blank=True, max_length=9)),
                ('customer_mobile', models.BigIntegerField(blank=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.CharField(max_length=150)),
                ('customer_lastlogin', models.DateTimeField()),
            ],
        ),
    ]
