# Generated by Django 3.1 on 2020-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
