# Generated by Django 3.1 on 2020-09-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_number',
        ),
    ]
